name: Build

on: [push]

jobs:
  build:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}
    defaults:
      run:
        shell: ${{ matrix.platform.shell }}
    strategy:
      matrix:
        platform:
          - { name: Windows, os: windows-latest, shell: 'msys2 {0}', exe: fs-uae.exe }
          - { name: Linux, os: ubuntu-latest, shell: sh, exe: fs-uae }
          - { name: Mac, os: macos-11, shell: sh, exe: fs-uae }
    steps:
      # Linux
      - name: Update packages (Linux)
        run: sudo apt update
        if: runner.os == 'Linux'

      - name: Install Dependencies (Linux)
        run: >-
          sudo apt install
          autoconf
          automake
          build-essential
          clang
          gettext
          libfreetype6-dev
          libglew-dev
          libglib2.0-dev
          libjpeg-dev
          libmpeg2-4-dev
          libopenal-dev
          libpng-dev
          libsdl2-dev
          libsdl2-ttf-dev
          libtool
          libxi-dev
          libxtst-dev
          zip
          zlib1g-dev
        if: runner.os == 'Linux'

      # Mac
      - name: Install Dependencies (Mac)
        run: >-
          brew install
          autoconf
          automake
          freetype
          gettext
          glew
          glib
          jpeg
          libmpeg2
          libpng
          libtool
          openal-soft
          pkg-config
          sdl2
          sdl2_ttf
          zlib
        if: runner.os == 'macOS'

      # Windows:
      - name: Install Dependencies (Windows)
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            autoconf
            automake
            gettext
            libtool
            make
            mingw-w64-x86_64-freetype
            mingw-w64-x86_64-clang
            mingw-w64-x86_64-glew
            mingw-w64-x86_64-glib2
            mingw-w64-x86_64-libmpeg2
            mingw-w64-x86_64-libpng
            mingw-w64-x86_64-openal
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-SDL2_ttf
            pkg-config
            zip
        if: runner.os == 'Windows'

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Make
        run: |
          ./bootstrap
          ./configure
          make -j2 CC=clang CXX=clang++

      - name: Dist
        run: |
          strip ${{ matrix.platform.exe }}
          mkdir -p fs-uae-${{ matrix.platform.name }}
          mv ${{ matrix.platform.exe }} fs-uae-${{ matrix.platform.name }}/
          mv fs-uae.dat fs-uae-${{ matrix.platform.name }}/
          cp -r data fs-uae-${{ matrix.platform.name }}/data

      - name: Copy Dependencies (Mac)
        run: ci/make_portable.sh fs-uae-${{ matrix.platform.name }}/fs-uae
        if: runner.os == 'macOS'

      - name: Zip
        run: zip -r fs-uae-${{ matrix.platform.name }}.zip fs-uae-${{ matrix.platform.name }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: fs-uae-${{ matrix.platform.name }}
          path: fs-uae-${{ matrix.platform.name }}
